repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: ghcinewest
  description: testing githubs continuous integration
  author: dg
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
  is_nfcore: true
